### ISSUE TITLE
"errorCode": "USER_AUTHENTICATION_FAILED"

### ISSUE THREAD

**Issue by mcraj017** [docusign/eg-01-java-jwt#6]
I am following the same code as in Examplebase class to get the JWT token and it suppose to renew the token after the token expired, but instead I am getting the following error after sometime.

com.docusign.esign.client.ApiException: Error while requesting server, received a non successful HTTP code 401 with response Body: '{
  "errorCode": "USER_AUTHENTICATION_FAILED",
  "message": "One or both of Username and Password are invalid. Invalid access token"
}'
	at com.docusign.esign.client.ApiClient.invokeAPI(ApiClient.java:1053)
	at com.docusign.esign.api.EnvelopesApi.createEnvelope(EnvelopesApi.java:701)
	at com.docusign.esign.api.EnvelopesApi.createEnvelope(EnvelopesApi.java:651)

**Comment by mcraj017** [comment]
asked in stackoverflow
https://stackoverflow.com/questions/57782797/errorcode-user-authentication-failed
